// <auto-generated />
using System;
using FixFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FixFlow.Infrastructure.Migrations
{
    [DbContext(typeof(FixFlowDbContext))]
    [Migration("20260922152152_AddAuthAndWorkflowSupport")]
    partial class AddAuthAndWorkflowSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FixFlow.Domain.Entities.AiWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("approval_status");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_step");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("finished_at");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("objective");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("plan_json");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_ai_workflows");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_ai_workflows_request_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_ai_workflows_status");

                    b.ToTable("ai_workflows", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.AiWorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentRole")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_role");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("input_summary");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("output_json");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<string>("ToolArgsSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("tool_args_summary");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tool_name");

                    b.Property<string>("ToolResultSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("tool_result_summary");

                    b.Property<string>("ValidationJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_json");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_ai_workflow_steps");

                    b.HasIndex("WorkflowId", "Timestamp")
                        .HasDatabaseName("ix_ai_workflow_steps_workflow_id_timestamp");

                    b.ToTable("ai_workflow_steps", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_workflow_steps_attempt", "attempt >= 1");

                            t.HasCheckConstraint("ck_ai_workflow_steps_duration", "duration_ms >= 0");
                        });
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("decision");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_approvals");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_approvals_actor_id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_approvals_booking_id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_approvals_request_id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("ix_approvals_workflow_id");

                    b.ToTable("approvals", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_audit_logs_actor_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.HasIndex("Entity", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AddressReleaseAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("address_release_at");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quotation_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_bookings_customer_id");

                    b.HasIndex("QuotationId")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_quotation_id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_request_id");

                    b.HasIndex("TechnicianId", "Status")
                        .HasDatabaseName("ix_bookings_technician_id_status");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("from_status");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("to_status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_booking_status_history");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_booking_status_history_actor_id");

                    b.HasIndex("BookingId", "Timestamp")
                        .HasDatabaseName("ix_booking_status_history_booking_id_timestamp");

                    b.ToTable("booking_status_history", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.CategoryVerificationRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("evidence_type");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rule_version");

                    b.Property<string>("ValidationMethod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("validation_method");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_category_verification_requirements");

                    b.HasIndex("CategoryId", "EvidenceType")
                        .IsUnique()
                        .HasDatabaseName("ix_category_verification_requirements_category_id_evidence_type");

                    b.ToTable("category_verification_requirements", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<Guid>("ReportedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_complaints");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_complaints_booking_id");

                    b.HasIndex("ReportedById")
                        .HasDatabaseName("ix_complaints_reported_by_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_complaints_status_created_at");

                    b.ToTable("complaints", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("ix_notifications_user_id_is_read_created_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArrivalStart")
                        .HasColumnType("timestamptz")
                        .HasColumnName("arrival_start");

                    b.Property<string>("Assumptions")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("assumptions");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<decimal>("LabourAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("labour_amount");

                    b.Property<decimal>("MaterialsAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("materials_amount");

                    b.Property<Guid>("QuoteGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_group_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("TravelAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("travel_amount");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_quotations");

                    b.HasIndex("InvitationId")
                        .HasDatabaseName("ix_quotations_invitation_id");

                    b.HasIndex("QuoteGroupId")
                        .HasDatabaseName("ix_quotations_quote_group_id");

                    b.HasIndex("TechnicianId")
                        .HasDatabaseName("ix_quotations_technician_id");

                    b.HasIndex("RequestId", "TechnicianId")
                        .HasDatabaseName("ix_quotations_request_id_technician_id");

                    b.ToTable("quotations", null, t =>
                        {
                            t.HasCheckConstraint("ck_quotations_amounts", "labour_amount >= 0 AND materials_amount >= 0 AND travel_amount >= 0 AND total_amount >= 0");

                            t.HasCheckConstraint("ck_quotations_duration", "duration_minutes > 0");
                        });
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.RequestClarification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_request_clarifications");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_request_clarifications_author_id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_request_clarifications_request_id");

                    b.ToTable("request_clarifications", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.RequestInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_request_invitations");

                    b.HasIndex("TechnicianId")
                        .HasDatabaseName("ix_request_invitations_technician_id");

                    b.HasIndex("RequestId", "TechnicianId")
                        .IsUnique()
                        .HasDatabaseName("ix_request_invitations_request_id_technician_id");

                    b.ToTable("request_invitations", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.RequestMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_request_media");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_request_media_request_id");

                    b.ToTable("request_media", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.RequestStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("from_status");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("to_status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_request_status_history");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_request_status_history_actor_id");

                    b.HasIndex("RequestId", "Timestamp")
                        .HasDatabaseName("ix_request_status_history_request_id_timestamp");

                    b.ToTable("request_status_history", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("ModerationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("moderation_reason");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_reviews_one_active_per_booking")
                        .HasFilter("status IN ('PENDING', 'PUBLISHED')");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_reviews_customer_id");

                    b.HasIndex("TechnicianId")
                        .HasDatabaseName("ix_reviews_technician_id");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviews_rating", "rating >= 1 AND rating <= 5");
                        });
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.ScopeChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("CustomerDecision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_decision");

                    b.Property<DateTimeOffset?>("DecisionAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decision_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<decimal>("ProposedCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("proposed_cost");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_scope_change_requests");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_scope_change_requests_booking_id");

                    b.ToTable("scope_change_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_scope_change_requests_cost", "proposed_cost >= 0");
                        });
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_service_categories");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_service_categories_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_service_categories_name");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_service_categories_parent_id");

                    b.ToTable("service_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3c1e8d0-1f44-4b6a-9c21-0b7d2e4f1101"),
                            Description = "Electrical installation and repair",
                            IsActive = true,
                            Name = "Electrician"
                        },
                        new
                        {
                            Id = new Guid("a3c1e8d0-1f44-4b6a-9c21-0b7d2e4f1102"),
                            Description = "Plumbing installation and repair",
                            IsActive = true,
                            Name = "Plumber"
                        },
                        new
                        {
                            Id = new Guid("a3c1e8d0-1f44-4b6a-9c21-0b7d2e4f1103"),
                            Description = "Air conditioning and refrigeration services",
                            IsActive = true,
                            Name = "AC/Refrigeration"
                        },
                        new
                        {
                            Id = new Guid("a3c1e8d0-1f44-4b6a-9c21-0b7d2e4f1104"),
                            Description = "Solar panel installation and maintenance",
                            IsActive = true,
                            Name = "Solar"
                        },
                        new
                        {
                            Id = new Guid("a3c1e8d0-1f44-4b6a-9c21-0b7d2e4f1105"),
                            Description = "Carpentry and woodwork",
                            IsActive = true,
                            Name = "Carpenter"
                        },
                        new
                        {
                            Id = new Guid("a3c1e8d0-1f44-4b6a-9c21-0b7d2e4f1106"),
                            Description = "Interior and exterior painting",
                            IsActive = true,
                            Name = "Painter"
                        },
                        new
                        {
                            Id = new Guid("a3c1e8d0-1f44-4b6a-9c21-0b7d2e4f1107"),
                            Description = "Home appliance diagnostics and repair",
                            IsActive = true,
                            Name = "Appliance Repair"
                        });
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressEncrypted")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("address_encrypted");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTimeOffset?>("PreferredEnd")
                        .HasColumnType("timestamptz")
                        .HasColumnName("preferred_end");

                    b.Property<DateTimeOffset?>("PreferredStart")
                        .HasColumnType("timestamptz")
                        .HasColumnName("preferred_start");

                    b.Property<string>("ServiceArea")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service_area");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_service_requests");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_service_requests_category_id");

                    b.HasIndex("CustomerId", "Status")
                        .HasDatabaseName("ix_service_requests_customer_id_status");

                    b.ToTable("service_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_requests_latitude", "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)");

                            t.HasCheckConstraint("ck_service_requests_longitude", "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)");

                            t.HasCheckConstraint("ck_service_requests_preferred_window", "preferred_start IS NULL OR preferred_end IS NULL OR preferred_end >= preferred_start");
                        });
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.TechnicianCategoryApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<string>("DecisionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("decision_notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_technician_category_applications");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_technician_category_applications_category_id");

                    b.HasIndex("DecidedBy")
                        .HasDatabaseName("ix_technician_category_applications_decided_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_technician_category_applications_status");

                    b.HasIndex("TechnicianId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_technician_category_applications_technician_id_category_id");

                    b.ToTable("technician_category_applications", null, t =>
                        {
                            t.HasCheckConstraint("ck_technician_category_applications_status", "status IN ('DRAFT', 'SUBMITTED', 'MORE_INFORMATION_REQUIRED', 'APPROVED', 'REJECTED', 'REVERIFICATION_REQUIRED', 'SUSPENDED')");
                        });
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.TechnicianDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("ClaimNumberEncrypted")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("claim_number_encrypted");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("evidence_type");

                    b.Property<string>("Issuer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuer");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mime_type");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("review_status");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_technician_documents");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_technician_documents_application_id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_technician_documents_sha256");

                    b.ToTable("technician_documents", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.TechnicianProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("average_rating");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("ExperienceSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("experience_summary");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suspended");

                    b.Property<double?>("LatitudeApprox")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude_approx");

                    b.Property<double?>("LongitudeApprox")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude_approx");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.Property<string>("ServiceArea")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("service_area");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_technician_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_technician_profiles_user_id");

                    b.ToTable("technician_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_technician_profiles_latitude", "latitude_approx IS NULL OR (latitude_approx >= -90 AND latitude_approx <= 90)");

                            t.HasCheckConstraint("ck_technician_profiles_longitude", "longitude_approx IS NULL OR (longitude_approx >= -180 AND longitude_approx <= 180)");
                        });
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('CUSTOMER', 'TECHNICIAN', 'ADMIN')");
                        });
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.VerificationCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("checked_at");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("outcome");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_reference");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_verification_checks");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("ix_verification_checks_admin_id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_verification_checks_application_id");

                    b.HasIndex("EvidenceId")
                        .HasDatabaseName("ix_verification_checks_evidence_id");

                    b.ToTable("verification_checks", (string)null);
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.AiWorkflow", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.ServiceRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ai_workflows_service_requests_request_id");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.AiWorkflowStep", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.AiWorkflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_workflow_steps_ai_workflows_workflow_id");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.Approval", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_users_actor_id");

                    b.HasOne("FixFlow.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_approvals_bookings_booking_id");

                    b.HasOne("FixFlow.Domain.Entities.ServiceRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_approvals_service_requests_request_id");

                    b.HasOne("FixFlow.Domain.Entities.AiWorkflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_approvals_ai_workflows_workflow_id");

                    b.Navigation("Actor");

                    b.Navigation("Booking");

                    b.Navigation("Request");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_users_actor_id");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.Booking", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_customer_id");

                    b.HasOne("FixFlow.Domain.Entities.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_quotations_quotation_id");

                    b.HasOne("FixFlow.Domain.Entities.ServiceRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_service_requests_request_id");

                    b.HasOne("FixFlow.Domain.Entities.TechnicianProfile", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_technician_profiles_technician_id");

                    b.Navigation("Customer");

                    b.Navigation("Quotation");

                    b.Navigation("Request");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.BookingStatusHistory", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_status_history_users_actor_id");

                    b.HasOne("FixFlow.Domain.Entities.Booking", "Booking")
                        .WithMany("StatusHistory")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_status_history_bookings_booking_id");

                    b.Navigation("Actor");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.CategoryVerificationRequirement", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.ServiceCategory", "Category")
                        .WithMany("VerificationRequirements")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_verification_requirements_service_categories_categ");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.Complaint", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_complaints_bookings_booking_id");

                    b.HasOne("FixFlow.Domain.Entities.User", "ReportedBy")
                        .WithMany()
                        .HasForeignKey("ReportedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_complaints_users_reported_by_id");

                    b.Navigation("Booking");

                    b.Navigation("ReportedBy");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.Quotation", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.RequestInvitation", "Invitation")
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_quotations_request_invitations_invitation_id");

                    b.HasOne("FixFlow.Domain.Entities.ServiceRequest", "Request")
                        .WithMany("Quotations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quotations_service_requests_request_id");

                    b.HasOne("FixFlow.Domain.Entities.TechnicianProfile", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quotations_technician_profiles_technician_id");

                    b.Navigation("Invitation");

                    b.Navigation("Request");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.RequestClarification", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_clarifications_users_author_id");

                    b.HasOne("FixFlow.Domain.Entities.ServiceRequest", "Request")
                        .WithMany("Clarifications")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_clarifications_service_requests_request_id");

                    b.Navigation("Author");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.RequestInvitation", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.ServiceRequest", "Request")
                        .WithMany("Invitations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_invitations_service_requests_request_id");

                    b.HasOne("FixFlow.Domain.Entities.TechnicianProfile", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_invitations_technician_profiles_technician_id");

                    b.Navigation("Request");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.RequestMedia", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.ServiceRequest", "Request")
                        .WithMany("Media")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_media_service_requests_request_id");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.RequestStatusHistory", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_request_status_history_users_actor_id");

                    b.HasOne("FixFlow.Domain.Entities.ServiceRequest", "Request")
                        .WithMany("History")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_status_history_service_requests_request_id");

                    b.Navigation("Actor");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.Review", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_bookings_booking_id");

                    b.HasOne("FixFlow.Domain.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_customer_id");

                    b.HasOne("FixFlow.Domain.Entities.TechnicianProfile", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_technician_profiles_technician_id");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.ScopeChangeRequest", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.Booking", "Booking")
                        .WithMany("ScopeChanges")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scope_change_requests_bookings_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.ServiceCategory", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.ServiceCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_categories_service_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.ServiceRequest", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.ServiceCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_service_requests_service_categories_category_id");

                    b.HasOne("FixFlow.Domain.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_requests_users_customer_id");

                    b.Navigation("Category");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.TechnicianCategoryApplication", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.ServiceCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_technician_category_applications_service_categories_categor");

                    b.HasOne("FixFlow.Domain.Entities.User", "DecisionMaker")
                        .WithMany()
                        .HasForeignKey("DecidedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_technician_category_applications_users_decided_by");

                    b.HasOne("FixFlow.Domain.Entities.TechnicianProfile", "Technician")
                        .WithMany("Applications")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_technician_category_applications_technician_profiles_techni");

                    b.Navigation("Category");

                    b.Navigation("DecisionMaker");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.TechnicianDocument", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.TechnicianCategoryApplication", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_technician_documents_technician_category_applications_appli");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.TechnicianProfile", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.User", "User")
                        .WithOne("TechnicianProfile")
                        .HasForeignKey("FixFlow.Domain.Entities.TechnicianProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_technician_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.VerificationCheck", b =>
                {
                    b.HasOne("FixFlow.Domain.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_verification_checks_users_admin_id");

                    b.HasOne("FixFlow.Domain.Entities.TechnicianCategoryApplication", "Application")
                        .WithMany("VerificationChecks")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_checks_technician_category_applications_applic");

                    b.HasOne("FixFlow.Domain.Entities.TechnicianDocument", "Evidence")
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_verification_checks_technician_documents_evidence_id");

                    b.Navigation("Admin");

                    b.Navigation("Application");

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.AiWorkflow", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.Booking", b =>
                {
                    b.Navigation("ScopeChanges");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("VerificationRequirements");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.ServiceRequest", b =>
                {
                    b.Navigation("Clarifications");

                    b.Navigation("History");

                    b.Navigation("Invitations");

                    b.Navigation("Media");

                    b.Navigation("Quotations");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.TechnicianCategoryApplication", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("VerificationChecks");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.TechnicianProfile", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("FixFlow.Domain.Entities.User", b =>
                {
                    b.Navigation("TechnicianProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
